Numpy - num+py

Numerical

Python


1. It is the scientific computing library for python .

2. It support large number of data in the form of multi- dimensional array & matrix.

3. It is used to perform mathematical calculation like:-

Linear Algebra

Fourier Transform

Random Number

How to create 1d array??

In [1]:
#import numpy lib
import numpy as np

In [9]:
arr_1d = np.array([1,2,3,4])

In [6]:
print(x)
#list = [1,2,3,4]

[1 2 3 4]


In [7]:
type(x)

numpy.ndarray

How to write 2d array??


In [20]:
arr_2d = np.array([[1,2,3,4],[2,6,7,8]])

In [21]:
print(arr_2d)

[[1 2 3 4]
 [2 6 7 8]]


In [19]:
type(arr_2d)

numpy.ndarray

In [22]:
#check the dimension of the array
x = arr_2d.ndim

In [23]:
print(x)

2


In [24]:
#task - Create a 1d array and check it dimension.

In [26]:
#check the size of array
a = arr_2d.size

In [27]:
print(a)

8


In [28]:
#check the shape of the array
shape = arr_2d.shape

In [29]:
print(shape)

(2, 4)


In [31]:
#check the datatype
dtype = arr_2d.dtype

In [32]:
print(dtype)

int64


In [33]:
#create 3d array
arr_3d = np.array([[[1,2,3],[2,3,4],[3,4,5]]])

In [34]:
print(arr_3d)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]]


In [35]:
#task - to create 3d array check the size,shape,ndim,dtype of the array.

In [38]:
arr_3d.shape

(1, 3, 3)

In [54]:
#creating identical n dimension array
a = np.ones((500,6))

In [55]:
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 ...
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [49]:
a.dtype

dtype('float64')

In [60]:
#change the datatype
a = np.ones((5,6),dtype = int)

In [61]:
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [79]:
#creating 0 n dimension array
a = np.zeros((3,8),dtype=int)

In [80]:
print(a)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [81]:
a.dtype

dtype('int64')

Numpy Function

1. arange

2. linspace

3. reshape

4. Transpose matrix/function

In [83]:
#arange - (1,10,2)  1,4,7   1,3,5,7,9
#range - (1,10)
a = np.arange(1,11,2)    # 1,3,5,7,9

In [84]:
print(a)

[1 3 5 7 9]


In [87]:
#linspace  (1,50,2)     (2,3,4)(3,8,6)
a = np.linspace(1,10,3)

In [89]:
print(a)         

[ 1.   5.5 10. ]


In [90]:
5.5-1

4.5

In [91]:
10-5.5

4.5

In [104]:
#reshape- Convert 1d into 2d
arr_1d = np.array([1,2,3,4,5,6,7,0])
arr_2d = arr_1d.reshape(2,4)

In [105]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 0]]


In [106]:
#transpose matrix / function
arr = np.array([[1,2,3],[7,8,9]])

In [107]:
arr.transpose()
#or

array([[1, 7],
       [2, 8],
       [3, 9]])

In [108]:
arr.T

array([[1, 7],
       [2, 8],
       [3, 9]])

Mathematical Opeartion using Numpy

1. Add

2. Sub

3. Multiply

4. Division

5. Dot product of Matrix

In [111]:
arr1 = np.arange(1,21).reshape(10,2)
arr2 = np.arange(1,21).reshape(10,2)
print(arr1)
print(arr2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [113]:
x = arr1+arr2

In [114]:
print(x)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]
 [30 32]
 [34 36]
 [38 40]]


In [115]:
#sub
#division
#multiplication
#dot product of matrix

x= np.arange(1,5).reshape(2,2)
y= np.arange(1,5).reshape(2,2)


In [116]:
#for dot product
a = x@y

In [117]:
print(a)

[[ 7 10]
 [15 22]]


In [118]:
#or
x.dot(y)

array([[ 7, 10],
       [15, 22]])